-- MySQL Script generated by MySQL Workbench
-- Wed Aug 24 19:34:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_shopping_list
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_shopping_list` ;

-- -----------------------------------------------------
-- Schema db_shopping_list
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_shopping_list` DEFAULT CHARACTER SET utf8 ;
USE `db_shopping_list` ;

-- -----------------------------------------------------
-- Table `db_shopping_list`.`Lista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shopping_list`.`Lista` (
  `lista_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lista_desc` VARCHAR(60) NOT NULL,
  `lista_valor_total` FLOAT NOT NULL,
  PRIMARY KEY (`lista_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shopping_list`.`Tipo_Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shopping_list`.`Tipo_Item` (
  `tipo_item_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_item_desc` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`tipo_item_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shopping_list`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shopping_list`.`Item` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `item_desc` VARCHAR(60) NOT NULL,
  `item_preco` FLOAT NOT NULL,
  `Tipo_Item_tipo_item_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_Item_Tipo_Item1_idx` (`Tipo_Item_tipo_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_Item_Tipo_Item1`
    FOREIGN KEY (`Tipo_Item_tipo_item_id`)
    REFERENCES `db_shopping_list`.`Tipo_Item` (`tipo_item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shopping_list`.`Lista_Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shopping_list`.`Lista_Item` (
  `Lista_lista_id` INT UNSIGNED NOT NULL,
  `Item_item_id` INT NOT NULL,
  `qtd_item` INT NOT NULL,
  `valor_total` FLOAT NOT NULL,
  PRIMARY KEY (`Lista_lista_id`, `Item_item_id`),
  INDEX `fk_Lista_has_Item_Item1_idx` (`Item_item_id` ASC) VISIBLE,
  INDEX `fk_Lista_has_Item_Lista1_idx` (`Lista_lista_id` ASC) VISIBLE,
  CONSTRAINT `fk_Lista_has_Item_Lista1`
    FOREIGN KEY (`Lista_lista_id`)
    REFERENCES `db_shopping_list`.`Lista` (`lista_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lista_has_Item_Item1`
    FOREIGN KEY (`Item_item_id`)
    REFERENCES `db_shopping_list`.`Item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
